"""Private D-ID Echo LiveKit sender. Runs only as an explicitly enabled local subprocess.

No browser gets echo_token, private audio or did.speak access. No TTS key enters this worker.
Protocol: single JSON request per stdin line, sanitized {id, ok} receipts on stdout.
"""
import asyncio
import base64
import binascii
import io
import json
import os
import sys
import wave
from urllib.parse import urlsplit

MAX_WAV_BYTES = 8 * 1024 * 1024
MAX_TEXT_BYTES = 4096
MAX_PENDING_UTTERANCES = 16
TTS_TIMEOUT_SECONDS = 35


def emit(identifier, ok):
    print(json.dumps({"id": identifier, "ok": bool(ok)}, separators=(",", ":")), flush=True)


def decode_audio(value):
    """Decode private bounded WAV generated by the shared Rust TtsPort."""
    if not isinstance(value, str) or len(value) > ((MAX_WAV_BYTES + 2) // 3) * 4:
        raise ValueError("oversized audio")
    try:
        wav_bytes = base64.b64decode(value, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ValueError("invalid encoded audio") from exc
    if len(wav_bytes) < 44 or len(wav_bytes) > MAX_WAV_BYTES:
        raise ValueError("invalid bounded WAV")
    if not wav_bytes.startswith(b"RIFF") or wav_bytes[8:12] != b"WAVE":
        raise ValueError("invalid WAV header")
    with wave.open(io.BytesIO(wav_bytes), "rb") as audio:
        if (
            audio.getcomptype() != "NONE"
            or audio.getsampwidth() != 2
            or audio.getnchannels() not in (1, 2)
            or audio.getframerate() < 8000
            or audio.getnframes() == 0
            or audio.getnframes() > audio.getframerate() * 60
        ):
            raise ValueError("unsupported audio format")
    return wav_bytes


async def run():
    from livekit import rtc

    raw = await asyncio.to_thread(sys.stdin.readline)
    initial = json.loads(raw)
    url = initial["session_url"]
    token = initial["echo_token"]
    if initial.get("command") != "open" or not isinstance(url, str):
        raise ValueError("invalid open")
    parts = urlsplit(url)
    if parts.scheme != "wss" or not parts.hostname or parts.username or parts.password:
        raise ValueError("invalid LiveKit origin")
    origin = url.split("/room/", 1)[0]
    room = rtc.Room()
    ready = asyncio.Event()
    room.on("track_subscribed", lambda *_: ready.set())
    try:
        await asyncio.wait_for(room.connect(origin, token), timeout=25)
        # D-ID drops audio published before its avatar media tracks are ready.
        await asyncio.wait_for(ready.wait(), timeout=25)
    except Exception:
        emit(initial.get("id", 0), False)
        await room.disconnect()
        return
    agents = [
        participant.identity
        for participant in room.remote_participants.values()
        if participant.kind == rtc.ParticipantKind.PARTICIPANT_KIND_AGENT
        or participant.identity.startswith("agent")
    ]
    if not agents:
        emit(initial.get("id", 0), False)
        await room.disconnect()
        return
    emit(initial.get("id", 0), True)

    utterance_lock = asyncio.Lock()
    tasks = {}
    generation = 0

    async def speak(identifier, wav_encoded, generation_at_start):
        writer = None
        try:
            # Serialize synthesis as well as sending. Otherwise a later,
            # faster TTS request can overtake an earlier spoken sentence.
            async with utterance_lock:
                if generation_at_start != generation:
                    emit(identifier, False)
                    return
                wav = await asyncio.to_thread(decode_audio, wav_encoded)
                if generation_at_start != generation:
                    emit(identifier, False)
                    return
                writer = await room.local_participant.stream_bytes(
                    name=f"rt0-utterance-{identifier}",
                    topic="did.audio-stream",
                    attributes={"format": "wav"},
                    destination_identities=agents,
                )
                # Backpressure from LiveKit bounds outbound sender memory.
                for offset in range(0, len(wav), 16 * 1024):
                    if generation_at_start != generation:
                        raise asyncio.CancelledError()
                    await writer.write(wav[offset:offset + 16 * 1024])
                await writer.aclose()
                writer = None
                # Closing a byte stream means D-ID received the utterance,
                # not that audio played. A concurrent STOP must not turn a
                # cancelled utterance into a successful sender receipt.
                if generation_at_start != generation:
                    emit(identifier, False)
                    return
                emit(identifier, True)
        except asyncio.CancelledError:
            emit(identifier, False)
        except Exception:
            emit(identifier, False)
        finally:
            if writer is not None:
                try:
                    await writer.aclose()
                except Exception:
                    pass
            # A stale task must never remove a newer task's ownership.
            if tasks.get(identifier) is asyncio.current_task():
                tasks.pop(identifier, None)

    try:
        while raw := await asyncio.to_thread(sys.stdin.readline):
            try:
                request = json.loads(raw)
                identifier = request["id"]
                command = request["command"]
                if command == "speak":
                    wav_encoded = request["audio_wav_base64"]
                    # Request IDs identify exactly one in-flight utterance. A duplicate
                    # must not replace its task or evade STOP/close cancellation.
                    if identifier in tasks or len(tasks) >= MAX_PENDING_UTTERANCES:
                        emit(identifier, False)
                        continue
                    if (
                        not isinstance(wav_encoded, str)
                        or not wav_encoded
                        or len(wav_encoded) > ((MAX_WAV_BYTES + 2) // 3) * 4
                    ):
                        emit(identifier, False)
                        continue
                    task = asyncio.create_task(speak(identifier, wav_encoded, generation))
                    tasks[identifier] = task
                elif command == "interrupt":
                    generation += 1
                    for task in tuple(tasks.values()):
                        task.cancel()
                    # This is a text STOP command, never browser-published audio.
                    await room.local_participant.send_text("{}", topic="did.interrupt")
                    emit(identifier, True)
                elif command == "close":
                    generation += 1
                    for task in tuple(tasks.values()):
                        task.cancel()
                    await room.local_participant.send_text("{}", topic="did.interrupt")
                    emit(identifier, True)
                    break
                else:
                    emit(identifier, False)
            except Exception:
                # No exception text, credentials or user speech in stdout.
                try:
                    emit(request.get("id", -1), False)
                except Exception:
                    pass
    finally:
        for task in tuple(tasks.values()):
            task.cancel()
        if tasks:
            await asyncio.gather(*tuple(tasks.values()), return_exceptions=True)
        await room.disconnect()


if __name__ == "__main__":
    try:
        asyncio.run(run())
    except Exception:
        # Process-level failure cannot be mistaken for a successful STOP.
        sys.exit(1)
